"""New Column size

Revision ID: d7fa51a53061
Revises: 2ad7bf20ca01
Create Date: 2021-11-15 20:14:58.421781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7fa51a53061'
down_revision = '2ad7bf20ca01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serie', sa.Column('size', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serie', 'size')
    # ### end Alembic commands ###
